### ISSUE TITLE
Feature Request; Add support for direct (2D) Scanning via Honeywell mobile devices

### ISSUE THREAD

**Issue by EddieSchrikenberg** [minvws/nl-covid19-coronacheck-app-android#82]
With the current version of the scanner app on Honeywell (Android Enterprise) Handheld Devices the camera is opened/launched to scan the QR barcode. For our customers it would be more ergonomic and more efficient (faster) if we could use the integrated 2D imager..

Could you please advice who to contact to explore the possibilities to include/embed scanner support for our handheld devices?
Of course we are happy to help/assist and/or provide you with all the necessary documentation and test hardware to support the development/implementation..

Many thanks in advance,

Eddie  Schrikenberg
Solution Architect
Honeywell | Productivity Solutions and Services
Burgermeester Burgerslaan 40
5245 NH  Rosmalen

**Comment by Yassineee** [comment]
I would like to advice to add support for all third party 2d scanners or external camera's. I already created an issue:
https://github.com/minvws/nl-covid19-coronacheck-app-android/issues/80

**Comment by EddieSchrikenberg** [comment]
Thanks Yassineee...
I would agree that support all 3rd party scanners/camera's would be the ideal solution. Unfortunately every vendor has its own implementation/methods (even when using intents).. 
Hence I started an separate request specifically for our products.

**Comment by royarisse** [comment]
I'd strongly advice against implementing external scanners. It'll open doors for malicious actors that might create their own implementations. They might forward the scanned data to their own databases for example.

Also, currently any user knows what the scanner app looks like, thus can distrust 'weird' looking apps. If there are many implementations this would no longer be the case.

**Comment by prlwtz** [comment]
@royarisse any external scanner can read the barcode into a database, irrespective of integration by this corona scanner app.
There is a difference between just reading the barcode and interpreting it. Only the corona check app can interpret the scanned data and the external scanner will not have access to that interpretation.

**Comment by prlwtz** [comment]
@Yassineee the embedded scanners such as in Honeywell and Zebra devices are not considered camera's. I understand the desire for integration of external camera's but in that case the corona app will still have to perform the analysis using its camera decoding library. 
The request for integration of native scanners on Honeywell and Zebra devices is a different angle. These scanners are much faster and easier to use and already decode the barcode for the application and just deliver the content to it.  Unfortunately, depsite these interfaces often looking similar, they slightly differ due to different vendor capabilities and history.

I have also seen a request for generic keyboard wedge integration so that many 3rd party scanners could be used. That won't work as the data in this barcode is binary and not transmittable as keyboard text.

**Comment by prlwtz** [comment]
@EddieSchrikenberg I have all the code ready for the integration of the Honeywell scanners. I just need to understand how to contribute it to this project.

**Comment by prlwtz** [comment]
@EddieSchrikenberg I have now uploaded and submitted a branch for review.

**Comment by royarisse** [comment]
@prlwtz Anyone can interpret the scanned QR code and it's data, it's an open standard after all.
I remain strongly against facilitating corona-scanner app duplicates.

**Comment by prlwtz** [comment]
@royarisse I was not aware the content was open standard too. I noticed something about certificates in the code, so I assumed it was all well protected by encryption. Anyways, if the goal is to prevent facilitating corona-scanner app duplicates, all of this should never have been made open source. Hardware is not the facilitating factor in this matter.

**Comment by EizeOostingHoneywell** [comment]
I will add support for Honeywell scanners

**Comment by BartNijland91** [comment]
Will be added in the next release, see https://github.com/minvws/nl-covid19-coronacheck-app-android/pull/92
